server:
  port: 11004
  # 2025年1004是樱和晓的生日

spring:
  profiles:
    active: @SakuraChoose@
    include: ai,mybatis,elasticsearch,rabbitmq,minio,redis

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 10GB

flow:
  jwt:
    secret: ${jwt.secret}
    expiration: ${jwt.expiration}
    
knife4j:
  basic:
    enable: false
ai:
  rag:
    context-limit: 3000
    max-docs: 5
