# 这是分环境配置的模板文件
mysql:
  host: localhost
  port: 3306
  username: root
  password: Flow_Mysql_1004

rabbitmq:
  host: localhost
  port: 5672
  username: flow_mq_admin
  password: flow_mq_1004

elasticsearch:
  uris: http://localhost:9200

redis:
  host: localhost
  port: 6379
  password: flow_redis_1004
  database: 0

minio:
  endpoint: http://localhost:9000
  access-key: flow_minio_admin
  secret-key: flow_minio_1004
  bucket-name: flow

jwt:
  secret: TenkouAkatsukiAndKasumiameSakuraTenkouAkatsukiAndKasumiameSakura
  expiration: 2592000000 # 30天

ai:
  openai:
    api-key: here-is-your-api-key
    base-url: https://generativelanguage.googleapis.com/v1beta/openai/
    model: models/gemini-2.5-flash
