services:
  mysql:
    image: mysql:8.0
    container_name: flow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Flow_Mysql_1004
      MYSQL_DATABASE: flow_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  minio:
    image: minio/minio
    container_name: flow-minio
    environment:
      MINIO_ROOT_USER: flow_minio_admin
      MINIO_ROOT_PASSWORD: flow_minio_1004
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: flow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: flow_mq_admin
      RABBITMQ_DEFAULT_PASS: flow_mq_1004
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: flow-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.11.1
    container_name: flow-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://flow-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  mysql_data:
  minio_data:
  es_data:
  rabbitmq_data:
